import { Inter } from 'next/font/google'
import './globals.css'
import Layout from '@/components/layout/Layout'
import AddTodo from '@/components/dialog/addTodo'
import EditTodo from '@/components/dialog/editTodo'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>

      <Layout>
      <AddTodo/>
      <EditTodo/>
        {children}
      </Layout>

        </body>
    </html>
  )
}
